### PR TITLE
Merge pull request #1 from redha1419/master

### PR DESCRIPTION
**Pull request by mruigrok**
getting up to date

### CODE REVIEW

**Comment by redha1419** [comment]
What was the change haha

**Comment by mruigrok** [comment]
Idk haha. I was just trying to pull the updated version to get sad at how
much work is left lol

**Comment by redha1419** [comment]
LOOL
are we gonna start working on this again ?

**Comment by mruigrok** [comment]
Idk man lol what do u think?
 Maybe just clean it up a bit and make a quick api. Take some pictures

**Pull request merged**
